name: PyInstaller Linux one dir release

on:
  workflow_dispatch:

jobs:
  pyinstaller-build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout app-builders-pyinstaller
        uses: actions/checkout@v5

      - name: Install dependencies and create one dir executable
        run: |
          echo "Install OS dependencies"
          sudo apt update
          sudo apt install espeak libespeak-dev espeak-data libespeak1 python3-dev
          echo "Creating Python Virtual environment..."
          python3 -m venv .venv
          source .venv/bin/activate
          echo "Install Python requirements... "
          pip install -r requirements.txt
          echo "Build Aeneas C extensions... "
          python setup.py build_ext --inplace

          echo "Create PyInstaller one directory executable"
          pyinstaller pyinstaller-onedir.spec --clean

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: aeneas-cli.linux.zip
          path: dist/aeneas-cli/
