name: PyInstaller Mac one dir release

on:
  workflow_dispatch:

jobs:
  pyinstaller-build:
    runs-on: macos-latest
    steps:
      - name: Checkout app-builders-pyinstaller
        uses: actions/checkout@v5

      - name: Install dependencies and create one dir executable
        run: |
          echo "Install OS dependencies"
          brew update && brew install espeak-ng python@3.14
          echo "Creating Python virtual environment... "
          python3.14 -m venv .venv 
          source .venv/bin/activate 
          echo "Install Python requirements... "
          pip install -r requirements.txt
          echo "Build Aeneas C extensions... "
          export LIBRARY_PATH=/opt/homebrew/lib
          python setup.py build_ext --inplace 

          echo "Create Pyinstaller one directory executable"
          pyinstaller pyinstaller-onedir.spec --clean

      - name: Tar build
        run: tar -cvf aeneas-cli.mac.tar ./dist/aeneas-cli

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: aeneas-cli.mac.tar
          path: aeneas-cli.mac.tar
