name: PyInstaller Windows one dir release

on:
  workflow_dispatch:

jobs:
  pyinstaller-build:
    runs-on: windows-latest
    steps:
      - name: Checkout app-builders-pyinstaller
        uses: actions/checkout@v5

      - name: Setup MSVC environment
        # This script sets up the correct environment variables, including PATH
        run: |
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x64
        shell: cmd

      - name: Install dependencies
        run: |
          echo "Install OS dependencies"
          choco install espeak-ng python
          refreshenv
          echo "Creating python Virtual environment... "
          python -m venv .venv 
          .venv\Scripts\activate
          echo "Install Python requirements... "
          pip install -r requirements.txt

      - name: Add Linking
        run: |
          echo "Add Linking for eSpeak-ng"
          link /libpath:"C:\Program Files\eSpeak NG"

      - name: Build PyInstaller one dir executable
        run: |
          echo "Build Aeneas C extensions... "
          python setup.py build_ext --inplace

          echo "Create PyInstaller one directory executable"
          pyinstaller pyinstaller-onedir.spec --clean

      - name: Tar build # It appears that windows has a tar command
        run: |
          cd dist
          tar -cvf aeneas-cli.win.tar aeneas-cli

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: aeneas-cli.win.tar
          path: dist/aeneas-cli.win.tar
