name: PyInstaller Windows one dir release

on:
  workflow_dispatch:

jobs:
  pyinstaller-build:
    runs-on: windows-latest
    steps:
      - name: Checkout app-builders-pyinstaller
        uses: actions/checkout@v5

      - name: Install dependencies and create one dir executable
        run: |
          echo "Install OS dependencies"
          choco install espeak-ng python ffmpeg
          New-Item -ItemType HardLink -Path "C:\Program Files\eSpeak NG\espeak.exe" -Target "C:\Program Files\eSpeak NG\espeak-ng.exe"
          echo "Creating python Virtual environment... "
          python -m venv .venv 
          .venv\Scripts\activate 
          echo "Install Python requirements... "
          pip install -r requirements.txt 
          echo "Build Aeneas C extensions... "
          python setup.py build_ext --inplace

          echo "Create PyInstaller one directory executable"
          pyinstaller pyinstaller-onedir.spec --clean

      - name: Tar build # It appears that windows has a tar command
        run: |
          cd dist
          tar -cvf aeneas-cli.win.tar aeneas-cli

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: aeneas-cli.win.tar
          path: dist/aeneas-cli.win.tar
