name: PyInstaller Windows one dir release

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

jobs:
  pyinstaller-build:
    runs-on: windows-self-hosted
    steps:
      - name: Checkout app-builders-pyinstaller
        uses: actions/checkout@v5

      - name: Install dependencies
        run: |
          echo "Install dependencies"
          python -m venv .venv 
          .venv\Scripts\activate 
          pip install -r requirements.txt 
          echo "Build Aeneas C extensions... "
          python setup.py build_ext --inplace

          echo "Create PyInstaller one directory executable"
          pyinstaller pyinstaller-onedir-win.spec --clean

          echo "Copy eSpeak NG files to aeneas-cli root"
          Copy-Item -Path "c:\program files\eSpeak ng\espeak-ng-data" -Destination "dist\aeneas-cli" -Recurse
          Copy-Item -Path "c:\program files\eSpeak ng\libespeak-ng.dll" -Destination "dist\aeneas-cli"
          Copy-Item -Path "c:\program files\eSpeak ng\espeak-ng.exe" -Destination "dist\aeneas-cli"

      #- name: Tar build # It appears that windows has a tar command
      # run: |
      #   cd dist
      #   tar -cvf aeneas-cli.win.tar aeneas-cli

      - name: Zip build output
        run: Compress-Archive -Path dist\aeneas-cli\* -DestinationPath aeneas-cli.win.zip

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: aeneas-cli.win.zip
          path: aeneas-cli.win.zip

      - name: Release
        uses: softprops/action-gh-release@v2.6.1
        if: github.ref_type == 'tag'
        with:
          files: aeneas-cli.win.zip
